import sys
import numpy as np

def find_neighbors(encoding):
    return [i for i, value in enumerate(encoding) if value == 1]
def floyd_warshall(adjacency_matrix, start):
    '''
    explores the maze using the floyd warshall algorithm and populates the distance matrix
    Inputs:
        adjacency_matrix: 2d array (dimension AxA where A is the number of nodes in the maze)
            representing the maze
        start: integer representing the index in the adjacency matrix of the start of the maze
    Outputs:
        steps: the number of steps the micromouse needs to explore the whole maze
        dist_matrix: 2d array (dimension AxA where A is the number of nodes in the maze)
            representing the distance between any 2 nodes in the maze
    '''
    #static variables
    graph_size = adjacency_matrix.shape
    incomplete_marker = graph_size[0] + 1

    #dynamic variables
    steps = 0
    dist_matrix = incomplete_marker*(np.ones(graph_size) - np.eye(graph_size[0]))
    unexplored_known_nodes = {};
    path = {}

    # node: connected node on path
    for neighbor in find_neighbors(adjacency_matrix[start][:]):
        unexplored_known_nodes.update({neighbor:start})
        dist_matrix[neighbor][start] = 1;
        dist_matrix[start][neighbor]= 1;

    # node: distance from current node
    path.update({start:0})
    
    while len(unexplored_known_nodes.keys()) > 0:
        # get the current node as the recent addition to the path
        current_node = list(path.keys())[-1]
        # look at the unexplored nodes and through the dist matrix to find the one thats closest to the current node
        # the closest one to current node would be the one that is connected to a node on path with a low distance from current node
        keys = list(unexplored_known_nodes.keys())
        values = list(unexplored_known_nodes.values())
        next_node = keys[values.index(min(values))]
        min_val = sys.maxsize
        next_node = None
        for node, connected_node in unexplored_known_nodes.items():
            if path[connected_node] < min_val:
                next_node = node
                min_val = path[connected_node]
        # check the path node the unexplored node and update path
        for node,distance_from_current in path.items():
            path[node] = dist_matrix[node][next_node]
        # add current node to path      
        path.update({next_node: 0})
        # add the distance from the current node to the next chosen node to steps. 
        steps = steps + dist_matrix[current_node][next_node]

        del unexplored_known_nodes[next_node]
        # add new neighbors to unexplored nodes if not aldready there.        
        # node: connected node on path)
        for neighbor in find_neighbors(adjacency_matrix[next_node][:]):
            # check if neighbor is discovered
            if not neighbor in path.keys():
                # update distances to elements on the path.
                for node, distance in path.items():
                    dist_matrix[neighbor][node] = 1 + distance;
                    dist_matrix[node][neighbor]= 1 + distance;

                # update distances to unexplored nodes
                for node, connected_node in unexplored_known_nodes.items():
                    dist_matrix[neighbor][node] = 2 + path[connected_node];
                    dist_matrix[node][neighbor]= 2 + path[connected_node];
                # add the neighbor to unexplored nodes
                unexplored_known_nodes.update({neighbor:next_node})

    return int(steps), dist_matrix

def shortest_path(dist_matrix, adjacency_matrix, start,end):
    '''
    finds the shortest path between the start node and the end node
    using the distance matrix generated by floyd warshall
    Inputs:
        dist_matrix: 2d array (dimension AxA where A is the number of nodes in the maze)
            representing the distance between any 2 nodes in the maze
        adjacency_matrix: 2d array (dimension AxA where A is the number of nodes in the maze)
            representing the maze
        start: integer representing the index in the adjacency matrix of the start of the maze
        end: integer representing the index in the adjacency matrix of the end of the maze
    Returns:
        Path: list of nodes representing the shortest path from start to end
    '''
    path = []
    current_node = start
    while not current_node == end:
        next_node = None
        dist = sys.maxsize
        for neighbor in find_neighbors(adjacency_matrix[current_node][:]):
            if dist_matrix[end][neighbor] < dist:
                dist = dist_matrix[end][neighbor]
                next_node = neighbor
        path.append(current_node)
        current_node = next_node
    path.append(end)
    return path

        
